bev:
  canvas_width: 800
  canvas_height: 800
  reference_rect:
    aspect_ratio: 2.54
    width_ratio: 0.4
cameras:
  front:
    file_name: sample1_front.mp4
    offset_frame: 0
    src_roi: [[126, 868], [56, 677], [1185, 673], [1122, 868]]
    dst_roi: [[337, 239], [288, 141], [506, 140], [464, 240]]
    H: [[-0.24226162597710701, -1.351777656496529, 568.9290812369796], [-0.0029370148743638287,
        -1.43426501294396, 795.0141883304337], [-4.355652420945487e-06, -0.003322053972302454,
        1.0]]
  back:
    file_name: sample1_back.mp4
    offset_frame: 0
    src_roi: [[128, 674], [368, 322], [908, 320], [1153, 672], [769, 769], [513, 769]]
    dst_roi: [[463, 562], [562, 700], [241, 702], [338, 561], [380, 562], [419, 562]]
    H: [[0.24233490716695638, -1.752127576997644, 243.9493221080615], [0.002544976053146536,
        -2.3202372855662605, 458.4987393707647], [1.6766698049006094e-06, -0.004383996867020164,
        1.0]]
  left:
    file_name: sample1_left.mp4
    offset_frame: 0
    src_roi: [[133, 955], [95, 652], [243, 571], [786, 900]]
    dst_roi: [[337, 275], [337, 558], [242, 677], [242, 275]]
    H: [[-0.04770954953427325, -0.7081066025941231, 334.32014727951463], [-0.17374457796407225,
        -0.1953707920302133, -74.50702728979154], [-0.0007425895284496949, -0.002025831320494314,
        0.9999999999999999]]
  right:
    file_name: sample1_right.mp4
    offset_frame: 0
    src_roi: [[1154, 955], [1190, 676], [1027, 636], [467, 892]]
    dst_roi: [[468, 279], [466, 561], [563, 692], [561, 279]]
    H: [[0.16364006387736976, -0.9516395784395453, 336.7274580465403], [0.013528294965579056,
        -0.3345393346182315, 75.39881841799895], [0.00012729516321040744, -0.0020584334788430482,
        1.0]]
